export const projects = [
  {
    name: "Hospital Appointment Management System",
    tag: "FULL-STACK",
    desc: "A full-stack hospital appointment platform with automated doctor scheduling, patient authentication, and seamless booking workflows. Secured with a scalable JWT architecture and PBAC for role-specific dashboards.",
    stack: [
      "Node.js",
      "Express.js",
      "MySQL",
      "Prisma",
      "JWT",
      "AWS EC2",
      "Nginx",
      "React.js",
      "Tailwind CSS",
      "ShadCN",
    ],
    featured: false,
    github: "https://github.com/venkateshmadari/hospital-management-website",
    website: "https://hospital-management-website-nine.vercel.app/",
    imagePath: "/project-1.png",
  },
  {
    name: "Production SaaS Platform",
    tag: "FRONTEND",
    desc: "Core features for a production SaaS platform at Spack Digi Solutions, spanning REST API services and the React.js/Next.js frontend, deployed on a highly available AWS architecture with edge caching and Redis.",
    stack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "TypeScript",
      "Sequelize",
      "MySQL",
      "Redis",
      "AWS",
      "k6",
    ],
    featured: false,
    github: "https://github.com/venkateshmadari/zeal-academy",
    website: "https://zeal-academy.vercel.app/",
    imagePath: "/project-2.png",
  },
];
export const stats = [
  ["2+", "Years experience"],
  ["15+", "Apps redesigned"],
  ["11.5M", "Requests load-tested"],
  ["3+", "Freelance projects"],
];
export const roles = [
  {
    t: "Full-Stack Developer",
    m: "Spack Digi Solutions · Oct 2025 – Present",
    d: "Built REST APIs and React/Next.js features for a production SaaS. Ran EC2 behind ASG + ALB with Nginx for zero-downtime scaling, cached public API responses at CloudFront (validated with k6 up to 11.5M requests at 99%+ success), added Redis via ElastiCache, and secured APIs with JWT, RBAC and PBAC.",
    s: [
      "Node.js",
      "Express.js",
      "TypeScript",
      "MySQL",
      "Sequelize",
      "AWS",
      "Nginx",
      "k6",
      "JWT",
      "RBAC",
      "PBAC",
    ],
  },
  {
    t: "Frontend Developer",
    m: "Spack Digi Solutions · May 2024 – Sept 2025",
    d: "Redesigned interfaces across 15+ applications with React.js and Tailwind CSS. Implemented permission-based access control and real-time features with Socket.IO, and integrated frontend with backend APIs.",
    s: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
      "Tailwind CSS",
    ],
  },
];
export const education = [
  {
    org: "Malla Reddy Engineering College",
    tag: "Hyderabad",
    t: "B.Tech, Electronics and Communication Engineering",
    d: "CGPA: 8.0/10",
    date: "Aug 2021 – Jun 2024",
    tags: ["B.Tech", "ECE"],
  },
  {
    org: "Achievement",
    tag: "Freelance",
    t: "Delivered 3+ freelance projects with 100% on-time completion",
    d: "Resulted in strong client referrals and repeat business.",
    date: "",
    tags: ["Freelance", "On-time delivery"],
  },
];

export const tech = [
  { name: "JavaScript", category: "Languages", color: "#F7DF1E" },
  { name: "TypeScript", category: "Languages", color: "#3178C6" },
  { name: "HTML5", category: "Languages", color: "#E34F26" },
  { name: "CSS3", category: "Languages", color: "#1572B6" },
  { name: "SQL", category: "Languages", color: "#336791" },

  { name: "React.js", category: "Frontend", color: "#61DAFB" },
  { name: "Next.js", category: "Frontend", color: "#FFFFFF" },
  { name: "Tailwind CSS", category: "Frontend", color: "#06B6D4" },
  { name: "Socket.IO", category: "Frontend", color: "#FFFFFF" },
  { name: "Responsive Design", category: "Frontend", color: "#8B5CF6" },

  { name: "Node.js", category: "Backend", color: "#339933" },
  { name: "Express.js", category: "Backend", color: "#FFFFFF" },
  { name: "REST APIs", category: "Backend", color: "#FF6B35" },
  { name: "JWT", category: "Backend", color: "#FB015B" },
  { name: "RBAC", category: "Backend", color: "#F59E0B" },
  { name: "PBAC", category: "Backend", color: "#F97316" },
  { name: "Prisma", category: "Backend", color: "#4AB1A7" },
  { name: "Sequelize", category: "Backend", color: "#52B0E7" },

  { name: "MySQL", category: "Databases", color: "#4479A1" },
  { name: "Redis", category: "Databases", color: "#DC382D" },

  { name: "EC2", category: "DevOps & Tools", color: "#FF9900" },
  { name: "ASG", category: "DevOps & Tools", color: "#FF9900" },
  { name: "ALB", category: "DevOps & Tools", color: "#FF9900" },
  { name: "RDS", category: "DevOps & Tools", color: "#527FFF" },
  { name: "S3", category: "DevOps & Tools", color: "#569A31" },
  { name: "CloudFront", category: "DevOps & Tools", color: "#FF9900" },
  { name: "Route 53", category: "DevOps & Tools", color: "#8C4FFF" },
  { name: "Nginx", category: "DevOps & Tools", color: "#009639" },
  { name: "Git", category: "DevOps & Tools", color: "#F05032" },
  { name: "GitHub", category: "DevOps & Tools", color: "#FFFFFF" },
  { name: "Postman", category: "DevOps & Tools", color: "#FF6C37" },
  { name: "k6", category: "DevOps & Tools", color: "#7D64FF" },
];
